language: python
python:
- '3.6'
cache: pip
script:
- script/test
deploy:
  provider: pypi
  skip_cleanup: true
  skip_existing: true
  user: Anne.Schuth
  password:
    secure: RIzts/ie1ydPCG5HK3BabybV7BzSHfOPze2qDwaF2R/W0LnBYSQapr1qeqXDO9QPHIeVEE6gTg1Z4VCEjEZGPu033haVRnug2srrW++td9rh9+yGDvC9NF2+8wd2Jbs+CVxzndpR05CzchUYByNhZ6LwMTDJ34qoPPEA7yEyHILA7afkU5tapeNnd6aTKTB9C+u3kizP+Pv0Ax+TgZ0I/ZsHORUWgoBKsnr17NPHn/IeP5lVgDoO7kKWPjjCrQ8phz9gmtdTyUVLlXHqn5hvxIEQFwQRVh3lQCqFBnykYtkIJaGVO/nBDDDIkrXcOqZOOfl4Siwgpvpz5xdL/gg3xmSpgoL4qO9lRBMQgBVDV/0dp88wgOFITM+DMFbn4GNAh1B2IUU0ExM4Ykv7aiHlptkadARwOsQLsWKv8vAd/sNrFLGGQ56C8ohb4410vUpDHYXvZ46bw1WcIMujNAEMWkZd4vKD8j/FW8lOC21KMfyzfQNWrh907XkFra3QXL20DlifXw2+dcLDLqd9miEkU3X20VQvOvnJV+/xs6NCtpTk/nVFBanyyx6DMD//rHf9xCDoYtBuArdZ3mDIr8C6BzlVPnq0xxzPcWq98XbVg0g309ywDKlwp8PGBzqzIzijRDdt2s4T9N4Kkuu2ZgkgJRCxKQD/jW3tiFvEJeQYvEM=
  on:
    branch: master
